apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mtjyph7rp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mtjyph7rp-go 
  name: mtjyph7rp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mtjyph7rp-go 
